### ISSUE TITLE
what am I doing wrong?

### ISSUE THREAD

**Issue by yegor256** [grosser/cachy#11]
```
puts Cachy.cache(:hey, expires_in: 1) { Random.rand(100) }
sleep 5
puts Cachy.cache(:hey, expires_in: 1) { Random.rand(100) }
```

I expect to see two different numbers. However, I see the same numbers. Why the first one is not expired?

@grosser please, help me understand...

**Comment by grosser** [comment]
All it does is `cache_store.write key, result, options` ... so try this and see if it expires, my guess would be that it does not

**Comment by yegor256** [comment]
@grosser it doesn't. Any ideas how to fix that?

**Comment by grosser** [comment]
that's an issue for whatever cache store you are using ... maybe it simply does not support expires_in
